In [2]:
#Q1)
import numpy as np 

def conv(a):
    return a.reshape(3, -1)

a=np.arange(12)
print(conv(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
#Q2)
import numpy as np

def replaceOdd(a):
    for i in range(a.size):
        if a[i]%2==1:
            a[i]=-1
    return a 

a=np.arange(10)
print(replaceOdd(a))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [4]:
#Q3)
import numpy as np

def compare(x, y):
    greater=[]
    equal=[]
    for i in range(x.size):
        if x[i]>y[i]:
            greater.append(i)
        elif x[i]==y[i]:
            equal.append(i)

    return np.array(greater), np.array(equal)

a=np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
b=np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(compare(a,b))

(array([1, 2, 4, 5, 6, 7, 8, 9]), array([0]))


In [5]:
#Q4)
import numpy as np

def first4col(a):
    result=[]
    for i in range(a.shape[0]):
        row=[]
        for j in range(4):
            row.append(a[i][j])
        result.append(row)
    
    return np.array(result)

print(first4col(np.arange(100).reshape(5,-1)))

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [6]:
#Additional Q1)
import numpy as np

def generateRand():
    return np.array(np.random.randint(30,40, 10))

print(generateRand())

[38 35 34 37 39 38 37 30 31 39]


In [7]:
#Additional Q2)
import numpy as np

A=np.array([[1,2,3],[4,5,6],[7,8,10]])
B=np.array([[7,8,10],[4,5,6],[1,2,3]])

C=A+B 
E=A-B 

print(C)
print('\n')
print(E)
print('\n')

sum_A=np.sum(A)
sum_B=np.sum(B, axis=0)
sum_C=np.sum(C, axis=1)
print(sum_A)
print(sum_B)
print(sum_C)
print('\n')

D = np.dot(A, B)
print(D)
print('\n')

E=np.sort(C,axis=None).reshape(C.shape)
print(E)
print('\n')

E_transpose = E.T
print(E_transpose)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]


[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


46
[12 15 19]
[31 30 31]


[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]


[[ 8  8  8]
 [10 10 10]
 [12 13 13]]


[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
